name: "nxs-backup"
version:
  major: 2
  minor: 5
  patch: 8
builds:
- name: "debian-9"
  deb:
    dh_make:
    - "--copyright=gpl3"
    - "--single"
    - "--templates=../build-scope/tpls/debian-9"
    - "--yes"
    - "--createorig"
    dpkg_buildpackage:
    - "-b"
    - "-us"
    - "-uc"
- name: "debian-10"
  deb:
    dh_make:
      - "--copyright=gpl3"
      - "--single"
      - "--templates=../build-scope/tpls/debian-10"
      - "--yes"
      - "--createorig"
    dpkg_buildpackage:
      - "-b"
      - "-us"
      - "-uc"
- name: "debian-11"
  deb:
    dh_make:
      - "--copyright=gpl3"
      - "--single"
      - "--templates=../build-scope/tpls/debian-11"
      - "--yes"
      - "--createorig"
    dpkg_buildpackage:
      - "-b"
      - "-us"
      - "-uc"
- name: "centos-7"
  rpm:
    cmake:
    - "-DRPM=on"
    - "."
    make:
    - "package"
